version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports: 
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST:-mrRabbit}
    networks:
      - app-network
    restart: unless-stopped

  sws-api:
    build:
      context: ./sws
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - app-network


  ocrworker:
    container_name: ocrworker
    build:
      context: ./OCRworker 
      dockerfile: ./Dockerfile
    environment:
      - MESSAGE_QUEUE_HOST=rabbitmq
      - OCR_CONFIG=default  # Any additional configurations
    depends_on:
      - rabbitmq
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80.
    volumes:
      - ./sws/nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./sws/wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - sws-api  # Ensure that the Nginx service starts after the API.
    networks:
      - app-network
    
  postgres:
    container_name: postgres  
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /data/postgres
    networks:
      - app-network
    restart: unless-stopped

  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      #  - ./docker-data/pgadmin/:/var/lib/pgadmin
      - ./sws/pgadmin-servers.json:/pgadmin4/servers.json

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  minio-data:
