version: '3.8'

services:
  sws-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80.
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Binde die Nginx-Konfigurationsdatei ein
      - ./wwwroot:/app/wwwroot  # Statische Dateien mounten
    depends_on:
      - sws-api  # Ensure that the Nginx service starts after the API.
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
